#ifndef _LMT01_CONFIG_H_
#define _LMT01_CONFIG_H_

// ACMP
#define LMT01_ACMP_DEV_INDEX                 0
#define LMT01_ACMP_INPUT_PORT                B
#define LMT01_ACMP_INPUT_PIN                 0
#define LMT01_ACMP_INPUT_BUSALLOC_INDEX      0

// COUNTER TIMER
#define LMT01_COUNTER_TIMER_INDEX            2

// ONESHOT TIMER
#define LMT01_ONESHOT_TIMER_PERIPHERAL_CLOCK 38400000LU
#define LMT01_ONESHOT_TIMER_INDEX            1


#endif
